ogp:
  site_name: "逆転教材"
  twitter_site: "@yoshito410kam"
  default_description: "人生逆転サロンの教材です"
genre:
  Basic: "Basic"
  Git: "Git"
  HTML&CSS: "HTML&CSS"
  Ruby: "Ruby"
  Ruby on Rails: "Ruby on Rails"
  Php: "PHP"
  Money: "マネタイズ講座"
  Talk: "対談"
  Live: "プログラミング勉強会"
  Marketing: "情報発信"
  Movie: "動画編集講座"
  Writing: "ライティング講座"
